import type { NextPage } from 'next'
import Head from 'next/head'
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { getComics } from 'dh-marvel/services/marvel/marvel.service';
import { useEffect, useState } from 'react';
import ResponsiveGrid from 'dh-marvel/components/Grid';

export async function getServerSideProps() {

    // getComics(0, 12).then((response) => {
    //     return {
    //         props: { comics: response.data.results },
    //     };
    // }
    // )

    const response = await getComics(0, 12)
      return {
        props:  { comics: response.data.results, count: response.data.count, total: response.data.total } ,
      };
}

type homeProps = {
    comics: any;
    count: number,
    total: number,
}

const Index: NextPage<any> = ({ comics }) => {
    console.log("🚀 ~ file: index.tsx:29 ~ comics:", comics)

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BodySingle title={"Welcome!"}>
                <ResponsiveGrid data={comics} />
            </BodySingle>
        </>
    )
}

export default Index
