import type { NextPage } from 'next'
import Head from 'next/head'
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { getComics } from 'dh-marvel/services/marvel/marvel.service';
import { useEffect, useState } from 'react';
import ResponsiveGrid from 'dh-marvel/components/Grid';
import PaginationOutlined from 'dh-marvel/components/Pagination';

const INITIAL_OFFSET = 0
const INITIAL_LIMIT = 12

export async function getServerSideProps() {
    const response = await getComics(INITIAL_OFFSET, INITIAL_LIMIT)
    return {
        props: {
            initialComics: response.data.results,
            limit: response.data.count,
            total: response.data.total
        },
    };
}

type indexProps = {
    initialComics: any;
    limit: number,
    total: number,
}

const Index: NextPage<indexProps> = ({ initialComics, limit, total }) => {
    const [comics, setComics] = useState(initialComics)
    const [page, setPage] = useState(1);

    function handleChange(page: number, event: any) {
        setPage(event)
    }

    async function handlePagination() {
        const response = await getComics((limit * page), limit)
        const results = await response.json()
        console.log(results)
        setComics(results)
    }

    async function getcomics() {
        const response = await getComics(0, 12)
        console.log("🚀 ~ file: index.tsx:45 ~ getcomics ~ response:", response?.data?.results)
    }

    useEffect(() => {
        // handlePagination()
        // getcomics().then(response => response?.data?.results)
    }, [])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BodySingle title={"Welcome!"}>
                <ResponsiveGrid data={comics} />
                <PaginationOutlined count={Math.round(total / 12)} page={page} handleChange={handleChange} />
            </BodySingle>
        </>
    )
}

export default Index
